type User {
  _id: ID
  username: String! @unique
  email: String!
  password: String!
  avatar: String
  joinDate: String
  favorites: [Blog]
}

type Blog {
  _id: ID
  title: String!
  imageUrl: String!
  categories: [String]!
  description: String!
  createdDate: String
  likes: Int
  createdBy: User!
  messages: [Message]
}

type Message {
  _id: ID
  messageBody: String!
  messageDate: String
  messageUser: User!
}

type Token {
  token: String!
}

type BlogPage {
  blogs: [Blog]
  hasMore: Boolean
}

type Query {
  getCurrentUser: User
  getBlogs: [Blog]
  infiniteScrollBlogs(pageNum: Int!, pageSize: Int!): BlogPage
}

type Mutation {
  addBlog(
    title: String!
    imageUrl: String!
    categories: [String]!
    description: String!
    creatorId: ID!
  ): Blog!
  signinUser(username: String!, password: String!): Token
  signupUser(username: String!, email: String!, password: String!): Token
}
